linktimecloud/kubernetes-data-platform

pkg/utils/utils.go
Fixes KDP src clone permission issue.
Local test by: `go run main.go install --debug --local-mode --set dnsService.name=kube-dns --force-reinstall`
=> Fix: repo clone permission

docs/en/user-tutorials/import-from-mysql-to-hive.md, docs/en/user-tutorials/import-from-mysql-to-kafka.md, docs/zh/user-tutorials/import-from-mysql-to-hive.md, docs/zh/user-tutorials/import-from-mysql-to-kafka.md
Correct and add some details in the tutorials
=> Fix: Correct and add some details in the tutorials

infra/kdp-core/template.cue
=> Fix: Fixed link text color

docs/en/user-tutorials/import-from-rbdms-to-hive.md, docs/zh/user-tutorials/import-from-rdbms-to-hive.md
Correct the position of "Flink on Hive" in the document.
=> Docs: Correct the position of "Flink on Hive" in the document

infra/kdp-core/resources/kdp-oam-operator.cue
=> Fix: oam-operator image.repository name

catalog/flink/apps/streampark.app/README.md, catalog/flink/apps/streampark.app/i18n/en/README.md, docs/en/catalog-overview/Flink/developer-guide.md, docs/zh/catalog-overview/Flink/developer-guide.md, docs/zh/user-tutorials/import-from-rdbms-to-hive.md
Fixes #TODO
Docs: Fix flink typo
=> Docs: Fix flink typo

infra/kdp-core/resources/kdp-oam-operator.cue
=> Fix: oam-operator controller/apiserver image repository does not match

docs/en/user-tutorials/import-from-rdbms-to-kafka.md, docs/zh/user-tutorials/import-from-rdbms-to-kafka.md
fix relative links in tutorials
=> Fix: fix relative links in tutorials

docs/en/user-tutorials/import-from-rdbms-to-kafka.md, docs/zh/user-tutorials/import-from-rdbms-to-kafka.md
This is a cherrypick from https://github.com/linktimecloud/kubernetes-data-platform/pull/45
=> Fix: cherrypick/fix relative links in tutorials

catalog/flink/x-definitions/app-streampark.cue, catalog/hdfs/x-definitions/app-httpfs.cue, catalog/hue/x-definitions/app-hue.cue
add missing k8s resources  for hue and streampark
Fixes #TODO
=> Fix: add missing k8s resources  for hue and streampark

catalog/flink/x-definitions/app-streampark.cue, catalog/hdfs/x-definitions/app-httpfs.cue, catalog/hue/x-definitions/app-hue.cue
Signed-off-by: xingcan-ltc <xingcan.hu@hotmail.com>
(cherry picked from commit 18b2fc371e25c7b8b19ba668f65b595c9213dcef)
Fixes #TODO
=> Fix: cherry pick #54 add missing k8s resources  for hue and streampark 

catalog/hive/x-definitions/app-hive-metastore.cue
Optimize the string format of hms-json-export.yml.
Will be cherry picked to the main branch after the merge.
=> Style: Optimize the string format of hms-json-export.yml to improve the maintainability of the code

catalog/hive/x-definitions/app-hive-metastore.cue
=> Refactor: improved hms-admin-cfg string format (#56)

infra/kdp-core/resources/kdp-catalog-manager.cue, infra/kdp-core/resources/kdp-ux.cue, infra/kdp-core/resources/shared-configs.cue, infra/kdp-core/template.cue, infra/openebs/parameter.cue, infra/openebs/template.cue, infra/plg-stack/parameter.cue, infra/plg-stack/resources/prometheus.cue
This PR adds support for KDP to integrate with mainstream K8s distributions, such as Kubesphere, Rancher K3s/RKE2.
E2E.
=> Feat: integration with mainstream K8s distributions

docs/en/user-tutorials/integration-kafka-with-int-ext-comps.md, docs/zh/user-tutorials/integration-kafka-with-int-ext-comps.md
Fixes kafka Integration with Internal and External Components docs
N/A
=> Docs: kafka integration doc

infra/plg-stack/resources/loki.cue
Fixes # delete loki grafana operator
=> Fix: delete loki grafana operator

docs/en/user-tutorials/import-from-hdfs-to-hdfs.md, docs/zh/user-tutorials/import-from-hdfs-to-hdfs.md
add description of flags to spark-distcp tutorials
=> Feat: add description of flags to spark-distcp tutorials

catalog/airbyte/x-definitions/app-airbyte.cue
=> Fix: add missing env parameters for airbyte

infra/kdp-core/template.cue
Feat # 
- add web terminal
- update catalog list
=> Feat: bumping kdp-core sub-components to v1.1.0

catalog/mysql/apps/mysql.app/app.yaml
Fixes # update mysql innodb_buffer_pool_size to reasonable range
=> Fix: update mysql innodb_buffer_pool_size to reasonable range

catalog/mysql/apps/mysql.app/app.yaml
=> Fix: update mysql innodb_buffer_pool_size to reasonable range (#85)

catalog/airbyte/x-definitions/app-airbyte.cue, catalog/superset/x-definitions/app-superset.cue
=> Chore: update superset airbyte apps image registry

catalog/flink/x-definitions/app-streampark.cue
=> Feat: add a startup probe for StreamPark in case it takes a long time to launch

catalog/airflow/apps/airflow.app/app.yaml, catalog/airflow/x-definitions/app-airflow.cue
- Fixes: Use init container to create database if not exist
- Fixes: Use mysql context setting/secret to get connection informations
- Fixes: change docker registry
=> Fix: airflow db initialization

catalog/airflow/apps/airflow.app/app.yaml, catalog/airflow/x-definitions/app-airflow.cue
- Fixes: Use init container to create database if not exist
- Fixes: Use mysql context setting/secret to get connection informations
- Fixes: change docker registry
=> Fix: airflow db initialization (#98)

catalog/airflow/x-definitions/app-airflow.cue
=> Chore: format airflow cue def

catalog/mysql/apps/mysql.app/app.yaml, catalog/mysql/x-definitions/app-mysql.cue
=> Fix: mysql arch should not be able to change after installation (#99)

catalog/flink/x-definitions/app-streampark.cue, catalog/hue/x-definitions/app-hue.cue, infra/kdp-core/definitions/trait-bdos-ingress.cue, infra/kong/template.cue
=> Fix: remove ingress trait parameter ingressClassName,  use k8s default class

catalog/flink/x-definitions/app-streampark.cue, catalog/hue/x-definitions/app-hue.cue, infra/kdp-core/definitions/trait-bdos-ingress.cue, infra/kong/template.cue
…t class (#110)
https://github.com/linktimecloud/kubernetes-data-platform/pull/110
Fixes #TODO
=> Fix(ingress): remove ingress trait parameter ingressClassName, use k8s default class

catalog/airflow/x-definitions/app-airflow.cue
…er launch arguments to decrease memory usage.
1. use the open-source Airflow Helm chart , do not use custom chart
2.  update the web server launch arguments to decrease memory usage (about 50 %). The default worker count is 4,  worker class is "sync". 
Fixes #TODO
=> Chore: use the open-source Airflow Helm chart and update the web server launch arguments to decrease memory usage

infra/kdp-core/template.cue
Fixes #deal with resource ownerReferences
=> Fix: deal with resource ownerReferences

catalog/mysql/x-definitions/app-mysql.cue
Fixes #delete nil for architecture list
=> Fix: delete nil for architecture list

infra/kdp-core/template.cue
Fixes # deal with resource ownerReferences
=> Fix: deal with resource ownerReferences (#121)

infra/kdp-core/template.cue
=> Fix: update kdp version

cmd/const.go
Fixes # update kdp cmd version
=> Fix: update kdp cmd version

catalog/hive/x-definitions/app-hive-metastore.cue
Add ttlSecondsAfterFinished for hms job
=> Feat: Add ttlSecondsAfterFinished for hms job

catalog/hue/x-definitions/app-hue.cue
Add a switch to enable/disable HDFS file browsing, 
as we sometimes use S3 objects as the storage layer instead of HDFS
Fixes #TODO
=> Feat(hue): Add a switch to enable/disable HDFS file browsing

infra/kdp-core/template.cue
Fixes # deal with the web terminal entry is restored to the original state
=> Fix: deal with the web terminal entry is restored to the original state

infra/kdp-core/template.cue
Fixes # deal with the web terminal entry is restored to the original state
=> Fix: deal with the web terminal entry is restored to the original state (#150)

catalog/juicefs/apps/juicefs-s3-gateway.app/README.md, catalog/juicefs/apps/juicefs-s3-gateway.app/i18n/en/README.md, catalog/juicefs/x-definitions/app-juicefs-s3-gateway.cue
=> Docs: fix  juicefs  doc typo

catalog/juicefs/x-definitions/app-juicefs-s3-gateway.cue, infra/fluxcd/template.cue, infra/kdp-core/template.cue, infra/kong/template.cue, infra/mysql/template.cue, infra/openebs/template.cue, infra/plg-stack/template.cue
Fixes # add policies enable parameter
=> Fix: add policies enable parameter

docs/en/user-tutorials/Real-time-incremental-data-analysis.md, docs/zh/user-tutorials/Real-time-incremental-data-analysis.md
Fixes: user-tutorials doc of real-time incremental data analysis
=> Fix: user-tutorials doc of real-time incremental data analysis

catalog/clickhouse/apps/clickhouse.app/app.yaml, catalog/flink/apps/flink-session-cluster.app/metadata.yaml, catalog/hive/apps/hive-metastore.app/metadata.yaml, catalog/hive/apps/hive-server2.app/metadata.yaml, catalog/spark/apps/spark-history-server.app/metadata.yaml
Fixes metadata of iceberg related images.
Clickhouse single instance by default.
=> Fix: fix metadata of iceberg related images

catalog/milvus/apps/milvus.app/README.md, catalog/milvus/apps/milvus.app/i18n/en/README.md, catalog/milvus/x-definitions/app-milvus.cue
=> Docs: fix milvus readme

docs/en/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md, docs/en/user-tutorials/visualization-analysis-of-taobao's-maternal-and-infant-shopping-data.md, docs/zh/user-tutorials/exploring-data-using-airbyte-clickhouse-superset.md, docs/zh/user-tutorials/visualization-analysis-of-taobao's-maternal-and-infant-shopping-data.md
=> Docs: fix user tutorials docs

infra/kdp-core/resources/kdp-cloudtty.cue
Fixes #deal with container creating
=> Fix: deal with job container creating

catalog/elasticsearch/apps/elasticsearch.app/app.yaml, catalog/elasticsearch/apps/elasticsearch.app/i18n/en/README.md, catalog/elasticsearch/apps/elasticsearch.app/metadata.yaml, catalog/elasticsearch/x-definitions/app-elasticsearch.cue, catalog/elasticsearch/x-definitions/setting-elasticsearch.cue
=> Docs(elasticsearch): fix description
